name: Config Tests
on: [push, pull_request]
jobs:
  Run-Config-Tests:
    runs-on: windows-latest
    steps:
      - name: STEP 1 - Check out repository code
        uses: actions/checkout@v2
      - name: STEP 2 - Check out salt repository
        run: git clone https://github.com/saltstack/salt.git ..\salt
      - name: STEP 3 - Create Mock Salt Repo
        run: |
          Write-Host "Creating mock salt-windows-nsis\build directory: " -NoNewLine
          New-Item -Path ..\salt-windows-nsis\build -Type Directory -Force | Out-Null
          Write-Host "Completed" -ForegroundColor Green
          Write-Host "Creating mock salt-windows-nsis\scripts directory: " -NoNewLine
          New-Item -Path ..\salt-windows-nsis\scripts -Type Directory -Force | Out-Null
          Write-Host "Completed" -ForegroundColor Green
          Write-Host "Copying mock files: " -NoNewLine | Out-Null
          Copy-Item -Path .\_mock_salt_pkg_windows\build\* -Destination ..\salt-windows-nsis\build\ -Recurse -Force | Out-Null
          Copy-Item -Path .\_mock_salt_pkg_windows\buildenv -Destination ..\salt-windows-nsis\scripts\ -Recurse -Force | Out-Null
          Write-Host "Completed" -ForegroundColor Green
      - name: STEP 4 - Build Test MSI
        run: .\build.cmd
      - name: STEP 5 - Run Config Tests
        run: .\test.cmd
